name: Publish Nuget Package

on:
  push:
    tags:
      - "*"
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version:
        description: "Enter version number, e.g. 1.2.3"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2
        
      - run: |
          echo "package_version=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: Build and Test
        run: dotnet build --configuration Release

      - name: Create the package
        run: dotnet pack --configuration Release src/Lykke.SettingsReader/Lykke.SettingsReader.csproj /p:Version=${{ env.package_version }}

      - name: Publish Nuget Package
        run: dotnet nuget push src/Lykke.SettingsReader/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
